name: Update

on:
  push:
  schedule:
    - cron: 30 20 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout
      uses: actions/checkout@v2
    - name: Step 2 - Build
      run: |
        rm -f Bench.sh
        wget https://ilemonra.in/LemonBenchIntl
        sed -i 's/System Information/系统信息:/' LemonBenchIntl
        sed -i 's/OS Release:/操作系统:/' LemonBenchIntl
        sed -i 's/CPU Model:/CPU型号:/' LemonBenchIntl
        sed -i 's/CPU Cache Size:/CPU缓存:\\t/' LemonBenchIntl
        sed -i 's/CPU Number:/CPU核心数:/' LemonBenchIntl
        sed -i 's/Virt Type:/虚拟化技术:/' LemonBenchIntl
        sed -i 's/Memory Usage:/内存使用情况:/' LemonBenchIntl
        sed -i 's/Swap Usage:/缓存使用情况:/' LemonBenchIntl
        sed -i 's/Boot Device:/启动盘:/' LemonBenchIntl
        sed -i 's/Disk Usage:/硬盘使用情况:/' LemonBenchIntl
        sed -i 's/CPU Usage:/CPU使用情况:/' LemonBenchIntl
        sed -i 's/Load (1\/5\/15min):/负载(1\/5\/15分钟):/' LemonBenchIntl
        sed -i 's/Uptime:/在线时长:/' LemonBenchIntl
        sed -i 's/Kernel Version:/内核版本:\\t/' LemonBenchIntl
        sed -i 's/Network CC Method:/拥塞控制算法:\\t/' LemonBenchIntl
        sed -i 's/Network Infomation/网络信息/' LemonBenchIntl
        sed -i 's/IP Address:/IP地址:\\t/' LemonBenchIntl
        sed -i 's/ASN Info:/ASN信息:/' LemonBenchIntl
        sed -i 's/Region:/地区:/' LemonBenchIntl
        sed -i 's/Media Unlock Test/流媒体解锁测试/' LemonBenchIntl
        sed -i 's/Bahamut Anime:/動畫瘋:/' LemonBenchIntl
        sed -i 's/BiliBili China Mainland Only:/哔哩哔哩大陆限定:\\t/' LemonBenchIntl
        sed -i 's/Bilibili China Mainland Only:/哔哩哔哩大陆限定:\\t/' LemonBenchIntl
        sed -i 's/BiliBili Hongkong\/Macau\/Taiwan:/哔哩哔哩港澳台区:\\t\\t/' LemonBenchIntl
        sed -i 's/Bilibili Hongkong\/Macau\/Taiwan:/哔哩哔哩港澳台区:\\t\\t/' LemonBenchIntl
        sed -i 's/Bilibili Taiwan Only:/哔哩哔哩台湾限定:/' LemonBenchIntl
        sed -i 's/CPU Performance Test/CPU性能测试/' LemonBenchIntl
        sed -i 's/Memory Performance Test/内存性能测试/' LemonBenchIntl
        sed -i 's/Thread Test/线程跑分/' LemonBenchIntl
        sed -i 's/1 Thread - Read Test /读取速度/' LemonBenchIntl
        sed -i 's/1 Thread - Write Test/写入速度/' LemonBenchIntl
        sed -i 's/Disk Speed Test/硬盘速度测试/' LemonBenchIntl
        sed -i 's/Test Name/测试内容/' LemonBenchIntl
        sed -i 's/Write Speed/写入速度/' LemonBenchIntl
        sed -i 's/Read Speed/读取速度/' LemonBenchIntl
        sed -i 's/Network Speed Test/网络速度测试/' LemonBenchIntl
        sed -i 's/Traceroute Test/路由跟踪测试/' LemonBenchIntl
        sed -i 's/Node Name/节点名称/' LemonBenchIntl
        sed -i 's/Upload Speed/上传速度/' LemonBenchIntl
        sed -i 's/Download Speed/下载速度/' LemonBenchIntl
        sed -i 's/Ping Latency/Ping延迟/' LemonBenchIntl
        sed -i 's/Server Name/服务器名称/' LemonBenchIntl
        sed -i 's/-g en/-g cn -a -l/' LemonBenchIntl
        sed -i 's/$3 $1/$3 $1 | nali/' LemonBenchIntl
        sed -i '/\[AD\]/d' LemonBenchIntl
        sed -i '/购买/d' LemonBenchIntl
        sed -i '1r ./.github/Mod' LemonBenchIntl
        mv LemonBenchIntl Bench.sh
    - name: Step 3 - Release
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update